name: output_route_selector
description: A Flutter plugin to select audio output routes (speaker, receiver, bluetooth, wired headset) on iOS and Android.
version: 1.1.1
homepage: https://github.com/raffazatyan/output_route_selector
repository: https://github.com/raffazatyan/output_route_selector

environment:
  sdk: ^3.10.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.raffazatyan.output_route_selector
        pluginClass: OutputRouteSelectorPlugin
      ios:
        pluginClass: OutputRouteSelectorPlugin
